### PR TITLE
udated sats.c

### PR DESCRIPTION
**Pull request by DarkStarp**

### CODE REVIEW

**Review by NeoAnoman — CHANGES_REQUESTED** [review]
make the stat structure globally since it will be used throughout the code.  
also before finalising the things please run the function on your system so that I don't have to check for any errors in the code.
Only submit the final code with no errors.

**Review by DarkStarp — COMMENTED** [review]
check the reset function of the user

**Comment by DarkStarp** [comment]
check the code again I have made changes

**Comment by NeoAnoman** [comment]
Good Keep up the good work...

**Pull request merged**
